# Generated by Django 5.2 on 2025-07-03 04:02

import movie_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["-update_time"],
                "verbose_name": "网文",
                "verbose_name_plural": "网文列表",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=movie_app.models.image_upload_path,
                verbose_name="封面图",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=200, verbose_name="网文名称"),
        ),
    ]
